apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: acp
  labels:
    app: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword" # Replace with a secure password
        # - name: MYSQL_DATABASE
        #   value: "counter_db" # Replace with your database name
        # - name: MYSQL_USER
        #   value: "root" # Replace with your username
        # - name: MYSQL_PASSWORD
        #   value: "rootpassword" # Replace with your password
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi # Adjust storage size as needed

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: acp
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306